import { supabase } from './supabase';

interface User {
  id: string;
  email: string;
  password: string;
  name?: string;
  role_id?: string;
  created_at?: string;
  [key: string]: any;
}

interface UserWithoutPassword extends Omit<User, 'password'> {}

interface Role {
  id: string;
  name: string;
  permissions?: string[];
  created_at?: string;
  [key: string]: any;
}

interface UserCreateData {
  email: string;
  password: string;
  name?: string;
  role_id?: string;
  [key: string]: any;
}

interface RoleCreateData {
  name: string;
  permissions?: string[];
  [key: string]: any;
}

const { data: users, error: userError } = await supabase
  .from('users')
  .select('*')
  .order('created_at', { ascending: false });

const { data: roles, error: roleError } = await supabase
  .from('roles')
  .select('*')
  .order('created_at', { ascending: false });

// Initialize with empty arrays if fetch failed
const usersData: User[] = users || [];
const rolesData: Role[] = roles || [];

export const db = {
  users: {
    findByEmail: (email: string): User | undefined => {
      console.log('Finding user by email:', email);
      const user = usersData.find(u => u.email === email);
      console.log('User found:', !!user);
      return user;
    },

    findById: (id: string): User | undefined => {
      return usersData.find(u => u.id === id);
    },

    getAll: (): UserWithoutPassword[] => {
      return usersData.map(({ password, ...user }) => user);
    },

    create: async (userData: UserCreateData): Promise<any | null> => {
      const { data, error } = await supabase.from('users').insert(userData);
      if (error) {
        console.error('Gagal menyisipkan data:', error);
        return null;
      }
      console.log('Data berhasil disisipkan:', data);
      return data;
    },

    update: (id: string, updates: Partial<User>): UserWithoutPassword | null => {
      const index = usersData.findIndex(u => u.id === id);
      if (index === -1) return null;
      usersData[index] = { ...usersData[index], ...updates };
      const { password, ...userWithoutPassword } = usersData[index];
      return userWithoutPassword;
    },

    delete: (id: string): boolean => {
      const index = usersData.findIndex(u => u.id === id);
      if (index === -1) return false;
      usersData.splice(index, 1);
      return true;
    },
  },

  roles: {
    findById: (id: string): Role | undefined => {
      console.log('Finding role by id:', id);
      const role = rolesData.find(r => r.id === id);
      console.log('Role found:', !!role);
      return role;
    },

    getAll: (): Role[] => {
      return rolesData;
    },

    create: (roleData: RoleCreateData): Role => {
      const newRole: Role = {
        id: '', // Should be generated by database
        ...roleData,
      };
      rolesData.push(newRole);
      return newRole;
    },

    update: (id: string, updates: Partial<Role>): Role | null => {
      const index = rolesData.findIndex(r => r.id === id);
      if (index === -1) return null;
      rolesData[index] = { ...rolesData[index], ...updates };
      return rolesData[index];
    },

    delete: (id: string): boolean => {
      const index = rolesData.findIndex(r => r.id === id);
      if (index === -1) return false;
      rolesData.splice(index, 1);
      return true;
    },
  },
};